name: Test Vercel Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test Vercel Token
        run: |
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "✅ VERCEL_TOKEN is set"
          else
            echo "❌ VERCEL_TOKEN is not set"
            exit 1
          fi
      
      - name: Test Vercel Org ID
        run: |
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "✅ VERCEL_ORG_ID is set"
          else
            echo "❌ VERCEL_ORG_ID is not set"
            exit 1
          fi
      
      - name: Test Frontend Project ID
        run: |
          if [ -n "${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}" ]; then
            echo "✅ VERCEL_PROJECT_ID_FRONTEND is set"
          else
            echo "❌ VERCEL_PROJECT_ID_FRONTEND is not set"
            exit 1
          fi
      
      - name: Show Secret Values (masked)
        run: |
          echo "Token length: ${#VERCEL_TOKEN}"
          echo "Org ID length: ${#VERCEL_ORG_ID}"
          echo "Frontend Project ID length: ${#VERCEL_PROJECT_ID_FRONTEND}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID_FRONTEND: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }} 