name: Test Vercel Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test Vercel Token
        run: |
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "✅ VERCEL_TOKEN is set"
          else
            echo "❌ VERCEL_TOKEN is not set"
            exit 1
          fi
      
      - name: Test Vercel Org ID (Personal Account)
        run: |
          echo "ℹ️  Using personal account - no org ID needed"
      
      - name: Test Frontend Project ID
        run: |
          if [ -n "${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}" ]; then
            echo "✅ VERCEL_PROJECT_ID_FRONTEND is set"
          else
            echo "❌ VERCEL_PROJECT_ID_FRONTEND is not set"
            exit 1
          fi
      
      - name: Test Backend Project ID
        run: |
          if [ -n "${{ secrets.VERCEL_PROJECT_ID_BACKEND }}" ]; then
            echo "✅ VERCEL_PROJECT_ID_BACKEND is set"
          else
            echo "❌ VERCEL_PROJECT_ID_BACKEND is not set"
            exit 1
          fi
      
      - name: Show Secret Values (masked)
        run: |
          echo "Token length: ${#VERCEL_TOKEN}"
          echo "Frontend Project ID length: ${#VERCEL_PROJECT_ID_FRONTEND}"
          echo "Backend Project ID length: ${#VERCEL_PROJECT_ID_BACKEND}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID_FRONTEND: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
          VERCEL_PROJECT_ID_BACKEND: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }} 